FROM node:20-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./
COPY tsconfig.json ./

# Instalar dependencias incluyendo las de desarrollo
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto de desarrollo
EXPOSE 3000

# Comando para iniciar la aplicación en modo desarrollo
CMD ["npm", "run", "dev"] 